{"name": "test_login_successful", "status": "broken", "statusDetails": {"message": "TypeError: 'set' object is not callable", "trace": "self = <test_requests.TestPostRequests object at 0x7f2e70f67eb0>\n\n    def test_login_successful(self):\n>       post_req = requests.post('https://reqres.in/api/login',\n                                 auth={'\"email\": \"eve.holt@reqres.in\",\"password\": \"cityslicka\"'},\n                                 headers={'Authorization': 'access_token QpwL5tke4Pnpja7X4'})\n\ntest_requests.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/usr/lib/python3/dist-packages/requests/api.py:119: in post\n    return request('post', url, data=data, json=json, **kwargs)\n/usr/lib/python3/dist-packages/requests/api.py:61: in request\n    return session.request(method=method, url=url, **kwargs)\n/usr/lib/python3/dist-packages/requests/sessions.py:516: in request\n    prep = self.prepare_request(req)\n/usr/lib/python3/dist-packages/requests/sessions.py:449: in prepare_request\n    p.prepare(\n/usr/lib/python3/dist-packages/requests/models.py:318: in prepare\n    self.prepare_auth(auth, url)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <PreparedRequest [POST]>, auth = {'\"email\": \"eve.holt@reqres.in\",\"password\": \"cityslicka\"'}, url = 'https://reqres.in/api/login'\n\n    def prepare_auth(self, auth, url=''):\n        \"\"\"Prepares the given HTTP auth data.\"\"\"\n    \n        # If no Auth is explicitly provided, extract it from the URL first.\n        if auth is None:\n            url_auth = get_auth_from_url(self.url)\n            auth = url_auth if any(url_auth) else None\n    \n        if auth:\n            if isinstance(auth, tuple) and len(auth) == 2:\n                # special-case basic HTTP auth\n                auth = HTTPBasicAuth(*auth)\n    \n            # Allow auth to make its changes.\n>           r = auth(self)\nE           TypeError: 'set' object is not callable\n\n/usr/lib/python3/dist-packages/requests/models.py:549: TypeError"}, "start": 1612135268879, "stop": 1612135268888, "uuid": "974731b5-f87a-4118-a1d5-20ab366d9387", "historyId": "0bf03f8d4576f56c8453a0b670f8705f", "testCaseId": "acad18ea64aea065d16dbb0009f02e76", "fullName": "api_testing.homework3.test_requests.TestPostRequests#test_login_successful", "labels": [{"name": "parentSuite", "value": "api_testing.homework3"}, {"name": "suite", "value": "test_requests"}, {"name": "subSuite", "value": "TestPostRequests"}, {"name": "host", "value": "kali"}, {"name": "thread", "value": "77832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_testing.homework3.test_requests"}]}